server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never
spring:
  application:
    name: node-message-broker
  data:
    mongodb:
      host: ${PERSISTENCE_HOSTNAME:localhost}
      port: ${PERSISTENCE_PORT:17017}
      database: ${PERSISTENCE_DATABASE_NAME:messagebroker}
logging:
  level:
    org.springframework.web: ${LOG_LEVEL:debug}

app:
  auth:
    jwksUrl: ${AUTH_JWKS_URL}
  hub:
    baseUrl: ${HUB_BASE_URL}
    auth:
      baseUrl: ${HUB_AUTH_BASE_URL}
      robotId: ${HUB_AUTH_ROBOT_ID}
      robotSecret: ${HUB_AUTH_ROBOT_SECRET}
    messenger:
      baseUrl: ${HUB_MESSENGER_BASE_URL}